apiVersion: v1
kind: Service
metadata:
  name: resume-svc
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: resume-port
  selector:
    org.oneacrefund.instance: {{ .Release.Name }}-resume
